### ISSUE TITLE
Lerna errors on install

### ISSUE THREAD

**Issue by rotu** [glslify/rollup-plugin-glslify#23]
This package fails to install from source when running install hooks:

https://github.com/plutotcool/glsl-bundler

```
npm ERR! > prepare
npm ERR! > lerna bootstrap
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm ERR! npm WARN deprecated @npmcli/ci-detect@1.4.0: this package has been deprecated, use `ci-info` instead
npm ERR! npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! lerna notice cli v4.0.0
npm ERR! lerna info Bootstrapping 3 packages
npm ERR! lerna info Installing external dependencies
npm ERR! lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in '@plutotcool/rollup-plugin-glsl'
npm ERR! lerna ERR! yarn install --mutex network:42424 --non-interactive stdout:
npm ERR! Unknown Syntax Error: Unsupported option name ("--mutex").
```

**Comment by rotu** [comment]
Oops. I meant to include: the command I ran to get the above was `npm install git+https://github.com/plutotcool/glsl-bundler` in an existing npm project.

**Comment by pschroen** [comment]
Hi @rotu, just taking a look now and not sure I follow, [glsl-bundler](https://github.com/plutotcool/glsl-bundler) is installing [rollup-plugin-glslify](https://github.com/glslify/rollup-plugin-glslify)?

From taking a look at the install hook, it looks like it's trying to install dependencies directly from the [packages](https://github.com/plutotcool/glsl-bundler/tree/main/packages) directory with a different [rollup-plugin-glsl](https://github.com/plutotcool/glsl-bundler/tree/main/packages/rollup-plugin-glsl)?

Not sure what the problem is though if you're looking for an upstream fix for installing with lerna, you could check with the [rollup-plugin-glsl](https://github.com/vwochnik/rollup-plugin-glsl) maintainer, though that plugin doesn't seem to be maintained anymore.

The @plutotcool/rollup-plugin-glsl appears to be a different plugin altogether, maintained by [plutotcool](https://github.com/plutotcool).

This plugin is specifically for [glslify](https://github.com/glslify/glslify).

**Comment by rotu** [comment]
@pschroen Oops! That's a PEBCAK error - I was trying a bunch of plugins and filed this issue against the wrong repo. I'm sorry and thank you for your patience!
